<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/18 12:32:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=admin_hackathon',
  'username' => 'admin_hackathon',
  'password' => 'hackathon',
  'name' => 'doctrine',
)),);
