<?php

/**
 * sensor_eventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sensor_eventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sensor_eventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sensor_event');
    }
}