<?php

/**
 * sensor_logTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sensor_logTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sensor_logTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sensor_log');
    }
}