generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Places
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          places
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        place_type: {help: 'inserire safe o control'}
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
