<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sensor_log', 'place_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sensor_log', 'place_id');
    }
}