<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sensor_event', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'temp' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'water' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'gas' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'earthquake' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'place_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('places', 'description');
        $this->removeColumn('places', 'emergency');
        $this->addColumn('users', 'state', 'string', '255', array(
             ));
        $this->changeColumn('sensor_log', 'temp', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->dropTable('sensor_event');
        $this->addColumn('places', 'description', 'clob', '', array(
             ));
        $this->addColumn('places', 'emergency', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('users', 'state');
    }
}