<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sensor_log', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'temp' => 
             array(
              'type' => 'double',
              'length' => '',
             ),
             'water' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'gas' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'earthquake' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'latitude' => 
             array(
              'scale' => '8',
              'type' => 'double',
              'length' => '',
             ),
             'longitude' => 
             array(
              'scale' => '8',
              'type' => 'double',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('sensor_log');
    }
}