<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('places', 'place_type', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('places', 'place_type');
    }
}