<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/18 12:32:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=h-emergenze',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
